import {ReactNode} from "react";

import type {Metadata} from "next";
import {Ubuntu_Sans} from "next/font/google";

import "./globals.scss";

const ubuntuSans = Ubuntu_Sans({
	variable: "--font-ubuntu-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="de" className={`${ubuntuSans.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
