#!/usr/bin/env node
import {mkdir, readFile, readdir, writeFile} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const svgDir = path.resolve(scriptDir, "../../src/pictograms");
const metaPath = path.resolve(scriptDir, "../../src/meta.json");
const outputPath = path.resolve(
	scriptDir,
	"../../src/generated/pictograms/traffic-style.ts",
);

/** Dark pictogram tones from Figma export → tinted via compose */
const DARK_COLOR = /^(?:#(?:000000|000|010101|241f20)|black)$/i;
/** Inline highlights inside dual-tone glyphs (e.g. schule head ring). */
const LIGHT_COLOR = /^(?:#(?:ffffff|fff)|white)$/i;

export function normalizePictogramColor(value: string): string {
	if (DARK_COLOR.test(value.trim())) {
		return "currentColor";
	}
	if (LIGHT_COLOR.test(value.trim())) {
		return "#ffffff";
	}
	return value;
}

export function normalizePictogramMarkup(markup: string): string {
	let result = markup
		.replace(/\sfill="([^"]+)"/gi, (_match, color: string) => {
			return ` fill="${normalizePictogramColor(color)}"`;
		})
		.replace(/\sstroke="([^"]+)"/gi, (_match, color: string) => {
			return ` stroke="${normalizePictogramColor(color)}"`;
		});

	// Filled paths without an explicit fill/stroke (SVG default = black).
	result = result.replace(
		/<(path|rect|circle|ellipse|polygon|polyline)(?![^>]*\sfill=)(?![^>]*\sstroke=)([^>]*)\/?>/gi,
		(_match, tag: string, rest: string) => {
			if (/\bd=["']/.test(rest)) {
				return `<${tag} fill="currentColor"${rest}>`;
			}
			return _match;
		},
	);

	return result.replace(/\s{2,}/g, " ").trim();
}

export function extractSvgParts(content: string): {
	viewBox: string;
	markup: string;
} {
	const viewBoxMatch = content.match(/viewBox="([^"]+)"/i);
	const viewBox = viewBoxMatch?.[1] ?? "0 0 24 24";
	const inner = content
		.replace(/^[\s\S]*?<svg\b[^>]*>/i, "")
		.replace(/<\/svg>\s*$/i, "");
	return {
		viewBox,
		markup: normalizePictogramMarkup(inner),
	};
}

type MetaIcon = {
	label?: Record<string, string>;
};

type SourceMeta = {
	icons?: Record<string, MetaIcon>;
};

async function main() {
	const metaContent = await readFile(metaPath, "utf8");
	const meta = JSON.parse(metaContent) as SourceMeta;

	const files = (await readdir(svgDir))
		.filter((name) => name.endsWith(".svg"))
		.sort();

	const lines = [
		'import type {PictogramDefinition} from "../../lib/pictograms/types.ts";',
		"",
		"/** Generated by scripts/dev/import-pictograms.ts — do not edit manually. */",
		"export const trafficStylePictograms: PictogramDefinition[] = [",
	];

	for (const fileName of files) {
		const id = fileName.replace(/\.svg$/i, "");
		const content = await readFile(path.join(svgDir, fileName), "utf8");
		const {viewBox, markup} = extractSvgParts(content);
		const label = meta.icons?.[id]?.label;

		lines.push("\t{");
		lines.push(`\t\tid: ${JSON.stringify(id)},`);
		if (label) {
			lines.push(`\t\tlabel: ${JSON.stringify(label)},`);
		}
		lines.push(`\t\tviewBox: ${JSON.stringify(viewBox)},`);
		lines.push('\t\tsource: "traffic-style",');
		lines.push(`\t\tmarkup: ${JSON.stringify(markup)},`);
		lines.push("\t},");
	}

	lines.push("];", "");

	await mkdir(path.dirname(outputPath), {recursive: true});
	await writeFile(outputPath, lines.join("\n"), "utf8");
	console.log(
		`Wrote ${files.length} traffic-style pictograms to ${outputPath}`,
	);
}

const isMain =
	process.argv[1] &&
	path.resolve(process.argv[1]) ===
		path.resolve(fileURLToPath(import.meta.url));

if (isMain) {
	main().catch((error: unknown) => {
		console.error(error);
		process.exitCode = 1;
	});
}
