#!/usr/bin/env node
import {mkdir, writeFile} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";

import {
	faBicycle,
	faBolt,
	faBus,
	faCar,
	faChargingStation,
	faHospital,
	faLocationDot,
	faMugHot,
	faSchool,
	faTree,
	faUtensils,
} from "@fortawesome/free-solid-svg-icons";
import type {IconDefinition} from "@fortawesome/free-solid-svg-icons";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(
	scriptDir,
	"../../src/generated/pictograms/fontawesome.ts",
);

type FaIconEntry = {
	exportName: string;
	id: string;
	label: Record<string, string>;
	icon: IconDefinition;
};

const icons: FaIconEntry[] = [
	{
		exportName: "faSchool",
		id: "fa-school",
		label: {de: "Schule", en: "School"},
		icon: faSchool,
	},
	{
		exportName: "faHospital",
		id: "fa-hospital",
		label: {de: "Krankenhaus", en: "Hospital"},
		icon: faHospital,
	},
	{
		exportName: "faBolt",
		id: "fa-bolt",
		label: {de: "Energie", en: "Energy"},
		icon: faBolt,
	},
	{
		exportName: "faCar",
		id: "fa-car",
		label: {de: "Auto", en: "Car"},
		icon: faCar,
	},
	{
		exportName: "faBicycle",
		id: "fa-bicycle",
		label: {de: "Fahrrad", en: "Bicycle"},
		icon: faBicycle,
	},
	{
		exportName: "faBus",
		id: "fa-bus",
		label: {de: "Bus", en: "Bus"},
		icon: faBus,
	},
	{
		exportName: "faChargingStation",
		id: "fa-charging-station",
		label: {de: "Ladestation", en: "Charging station"},
		icon: faChargingStation,
	},
	{
		exportName: "faUtensils",
		id: "fa-utensils",
		label: {de: "Gastronomie", en: "Restaurant"},
		icon: faUtensils,
	},
	{
		exportName: "faMugHot",
		id: "fa-cafe",
		label: {de: "Café", en: "Cafe"},
		icon: faMugHot,
	},
	{
		exportName: "faTree",
		id: "fa-tree",
		label: {de: "Park", en: "Park"},
		icon: faTree,
	},
	{
		exportName: "faLocationDot",
		id: "fa-marker",
		label: {de: "Marker", en: "Marker"},
		icon: faLocationDot,
	},
];

function iconToMarkup(icon: IconDefinition): {viewBox: string; markup: string} {
	const [width, height, , , pathData] = icon.icon;
	const paths = Array.isArray(pathData) ? pathData : [pathData];
	const markup = paths
		.map((d) => `<path fill="currentColor" d="${d}"/>`)
		.join("");
	return {
		viewBox: `0 0 ${width} ${height}`,
		markup,
	};
}

const lines = [
	'import type {PictogramDefinition} from "../../lib/pictograms/types.ts";',
	"",
	"/** Generated by scripts/dev/import-fontawesome.ts — do not edit manually. */",
	"export const fontAwesomePictograms: PictogramDefinition[] = [",
];

for (const entry of icons) {
	const {viewBox, markup} = iconToMarkup(entry.icon);
	lines.push("\t{");
	lines.push(`\t\tid: ${JSON.stringify(entry.id)},`);
	lines.push(`\t\tlabel: ${JSON.stringify(entry.label)},`);
	lines.push(`\t\tviewBox: ${JSON.stringify(viewBox)},`);
	lines.push('\t\tsource: "fontawesome",');
	lines.push(`\t\tmarkup: ${JSON.stringify(markup)},`);
	lines.push("\t},");
}

lines.push("];", "");

await mkdir(path.dirname(outputPath), {recursive: true});
await writeFile(outputPath, lines.join("\n"), "utf-8");
console.log(`Wrote ${icons.length} Font Awesome pictograms to ${outputPath}`);
