import uniq from "lodash/uniq.js";

import {ensureNonNullable} from "@mapsight/lib-js/nonNullable";
import trimQuotes from "@mapsight/lib-js/string/trimQuotes";
import isNumberLike from "@mapsight/lib-js/types/isNumberLike";

import type {ReplacerFn} from "../helpers/Replacer.ts";
import Replacer from "../helpers/Replacer.ts";
import pathToExpression from "../helpers/pathToExpression.ts";

const replace: ReplacerFn = (_match, parameter) => {
	const [search, replacement, subject] = parameter
		.split(",")
		.map((a) => a.trim())
		.map(trimQuotes);

	return `' + replace('${search}', '${replacement}', '${subject}') + '`;
};

const calc: ReplacerFn = (_match, parameter, replacer) => {
	// parameter is e.g. "%%%0%%% * 5"
	// Resolve the inner tags back to their actual string representations
	let resolvedParam = replacer.replace(parameter);

	// Clean up the string concatenations generated by the earlier `attr` pass.
	// It extracts `props['test']` out of `' + props['test'] + '`
	resolvedParam = resolvedParam.replace(/' \+ (.*?) \+ '/g, "$1");

	return `' + (${resolvedParam}) + '`;
};

export default function mapValue(
	value: string | number | null | undefined | boolean,
) {
	const meta = {
		styleProps: [] as Array<string>,
		stylePropExpressions: [] as Array<string>,
	};

	if (!value) {
		return {value: null, __meta: meta};
	}

	let valueStr = String(value);
	if (isNumberLike(value)) {
		return {value: parseFloat(valueStr), __meta: meta};
	}

	valueStr = trimQuotes(valueStr);
	const replacer = new Replacer([
		[
			"attr",
			(_match, parameter) => {
				const isEnv = parameter.startsWith("--env-");
				const parameters = parameter.split("-");

				if (isEnv) {
					const restParameters = parameters.slice(3);
					return `' + ${pathToExpression("env", restParameters)} + '`;
				}

				const expression = pathToExpression("props", parameters);
				meta.styleProps.push(ensureNonNullable(parameters[0]));
				meta.stylePropExpressions.push(expression);
				return `' + ${expression} + '`;
			},
		],
		["replace", replace],
		["calc", calc],
	]);
	valueStr = replacer.execute(valueStr);
	valueStr = valueStr.replace(/'/g, "\\'");
	valueStr = replacer.replace(valueStr);
	valueStr = `'${valueStr}'`;

	return {
		value: valueStr,

		__meta: {
			styleProps: uniq(meta.styleProps),
			stylePropExpressions: uniq(meta.stylePropExpressions),
		},
	} as const;
}
