name: Release Production Packages (@mapsight on npm)

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
          submodules: false
          fetch-depth: 0 # we need the full history to get the correct list of changed files

      - uses: ./.github/actions/setup/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1.8.0
        with:
          publish: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
